apiVersion: v1
kind: PersistentVolume
metadata:
  name: ide-efs-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-08bc5ee0b5a858212
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ide-efs-pvc
  namespace: ads-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 50Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-utils
  fileSystemId: fs-08bc5ee0b5a858212
  directoryPerms: "0755"
mountOptions:
  - tls
  - fsc
